# Generated by Django 4.1.2 on 2022-12-07 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment_details',
            name='time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
