# Generated by Django 4.1.2 on 2022-12-07 19:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='excel_data',
            name='user',
        ),
        migrations.AddField(
            model_name='excel_data',
            name='app_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='app_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='excel_data',
            name='writer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='writer', to=settings.AUTH_USER_MODEL),
        ),
    ]
