# Generated by Django 4.1.2 on 2022-12-07 19:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('web', '0002_remove_excel_data_user_excel_data_app_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='excel_data',
            name='main',
        ),
        migrations.CreateModel(
            name='Main_excel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.CharField(blank=True, max_length=100, null=True)),
                ('user', models.OneToOneField(db_column='user', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
